base/urls.py
from django.urls import path
from . import views

app_name = 'base'
urlpatterns = [
    # Страница авторизации
    path('logout/', views.logout_base, name='logout'),
    # Список заявок
    path('', views.ticket_index, name='ticket_index'),
    # фильтрованный список
    path('tickets/<str:index_filter>/', views.ticket_index, name='index_filter'),
    path('tickets/<str:index_filter>/<str:filter_str>/', views.ticket_index, name='index_filter'),
    # Окно заявки
    path('<int:ticket_id>/', views.ticket_detail, name='ticket_detail'),
    # Создание заявки
    path('newticket/', views.new_ticket, name='new_ticket'),
    # Закрытие заявки
    path('<int:ticket_id>/closed/', views.ticket_close, name='ticket_close'),
    # Изменение заявки
    path('<int:ticket_id>/changed/', views.ticket_edit, name='ticket_edit'),
    # Отчеты по заявкам
    path('summary/', views.ticket_summary, name="ticket_summary"),
    path('summary/<str:summary_filter>/', views.ticket_summary, name="ticket_summary"),
    path('summary/<str:summary_filter>/<str:summary_sort>', views.ticket_summary, name="ticket_summary"),
]

mlift/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view()),
    path('', include('base.urls')),
    path('admin/', admin.site.urls),
]

base/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class TicketStatus(models.Model):
    status = models.CharField(max_length=50)
    def __str__(self):
        return '%s' % (self.status)
    class Meta:
        verbose_name = "Статус заявки"
        verbose_name_plural = "Статусы заявок"


class TicketType(models.Model):
    type_name = models.CharField(max_length=50)
    def __str__(self):
        return 'Тип заявки: %s' % (self.type_name)
    class Meta:
        verbose_name = "Тип заявки"
        verbose_name_plural = "07. Типы заявок"


class ManageComp(models.Model):
    comp_name = models.CharField('Обслуживающая компания', max_length=100)
    decline_period = models.DurationField('Период простоя до акта снижения', default=timezone.timedelta(days = 1), null=True, blank=True)
    def __str__(self):
        return '%s' % (self.comp_name)
    class Meta:
        verbose_name = "Владелец"
        verbose_name_plural = "02. Владельцы"


class ObjArea(models.Model):
    area_name = models.CharField('Район', max_length=50)
    def __str__(self):
        return '%s' % (self.area_name)
    class Meta:
        verbose_name = "Район"
        verbose_name_plural = "02. Районы"

class ObjStr(models.Model):
    street = models.CharField('Улица', max_length=50)
    area = models.ForeignKey(ObjArea, on_delete=models.CASCADE, null=True, verbose_name='Район')
    def __str__(self):
        return '%s' % (self.street)
    class Meta:
        verbose_name = "Улица"
        verbose_name_plural = "02. Улицы"


class ObjType(models.Model):
    type_name = models.CharField('Тип лифта', max_length=20)
    def __str__(self):
        return '%s' % (self.type_name)
    class Meta:
        verbose_name = "Тип лифта"
        verbose_name_plural = "02. Типы лифтов"


class ObjManufacturer(models.Model):
    manufacturer = models.CharField('Завод производитель', max_length=50)
    def __str__(self):
        return '%s' % (self.manufacturer)
    class Meta:
        verbose_name = "Завод производитель"
        verbose_name_plural = "02. Заводы производители"


class ObjParField(models.IntegerField):
    def to_python(self, value, alter):
        if value is None:
            return value
        try:
            if alter:
                return chr(value+1039)
            else:
                return int(value)
        except (TypeError, ValueError):
            raise exceptions.ValidationError(
                self.error_messages['invalid'],
                code='invalid',
                params={'value': value},
            )


class Object(models.Model):
    obj_area = models.ForeignKey(ObjArea, on_delete=models.DO_NOTHING, null=True, verbose_name='Район')
    obj_str = models.ForeignKey(ObjStr, on_delete=models.DO_NOTHING, verbose_name='Улица')
    obj_build = models.CharField('Дом', max_length=15, null=True)
    obj_build_housing = models.CharField('Корпус', max_length=10, null=True, blank=True)
    obj_par_alter = models.BooleanField('Литеральный номер парадной', default=False, null=True, blank=True)
    obj_par = models.IntegerField('Номер парадной', null=True, blank=True) #Тут было ObjParField но нужно доделать альтернативные имена парадных
    obj_number = models.CharField('Номер лифта', max_length=15, null=True, blank=True)
    obj_factory_number = models.CharField('Заводской номер', max_length=15, null=True, blank=True)
    obj_type = models.ForeignKey(ObjType, on_delete=models.DO_NOTHING, null=True, verbose_name='Тип лифта', blank=True)
    obj_carrying = models.IntegerField('Грузоподъемность', null=True, blank=True)
    obj_aperture = models.IntegerField('Этажность', null=True, blank=True)
    obj_manufacturer = models.ForeignKey(ObjManufacturer, on_delete=models.DO_NOTHING, null=True, verbose_name='Завод производитель', blank=True)
    manage_comp = models.ForeignKey(ManageComp, on_delete=models.DO_NOTHING, null=True, verbose_name='Управляющая компания', blank=True)
    obj_communication = models.BooleanField('Наличие связи', null=True)
    obj_manufacture = models.DateTimeField('Дата производства', null=True, blank=True)
    obj_exp_start = models.DateTimeField('Дата начала эксплуатации', null=True, blank=True)
    obj_inspection = models.DateTimeField('Дата последней инспекции', null=True, blank=True)
    obj_in_service = models.BooleanField('Обслуживание')
    def __str__(self):
        return '№ %s улица %s дом %s' % (self.obj_number, self.obj_str, self.obj_build)
    class Meta:
        verbose_name = "Лифт"
        verbose_name_plural = "01. Лифты"


class Worker(models.Model):
    last_name = models.CharField('Фамилия', max_length=15)
    first_name = models.CharField('Имя', max_length=15)
    optional_name = models.CharField('Отчество', max_length=15, null=True, blank=True)
    worker_area = models.ForeignKey(ObjArea, on_delete=models.DO_NOTHING, verbose_name='Район работы')
    worker_recruitment = models.DateField('Дата приема на работу', null=True, blank=True)
    active = models.BooleanField('Активен', null=True, blank=True, default=True)
    phone_work = models.CharField('Рабочий телефон', max_length=11, null=True, blank=True)
    phone_alt = models.CharField('Дополнительный телефон', max_length=11, null=True, blank=True)
    def __str__(self):
        return '%s %s %s' % (self.last_name, self.first_name, self.optional_name)
    @property
    def full_name(self):
        return '%s %s' % (self.last_name, self.first_name)
    class Meta:
        verbose_name = "Работник"
        verbose_name_plural = "08. Работники"


class Ticket(models.Model):
    ticket_date = models.DateTimeField('Дата публикации')
    ticket_user = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name='Автор')
    ticket_object = models.ForeignKey(Object, on_delete=models.CASCADE, verbose_name='Объект заявки', null=True, blank=True)
    ticket_str = models.ForeignKey(ObjStr, on_delete=models.DO_NOTHING, verbose_name='Улица')
    ticket_build = models.CharField('Дом', max_length=15, default='-')
    ticket_build_housing = models.CharField('Корпус', max_length=10, blank=True, null=True)
    ticket_par = models.IntegerField('Парадная', blank=True, null=True)
    ticket_obj_type = models.ForeignKey(ObjType, on_delete=models.DO_NOTHING, verbose_name='Тип лифта', blank=True, null=True)
    ticket_type = models.ForeignKey(TicketType, on_delete=models.DO_NOTHING, verbose_name='Тип заявки', blank=True, null=True)
    ticket_content = models.CharField('Содержание', max_length=1000, blank=True)
    ticket_status = models.ForeignKey(TicketStatus, on_delete=models.DO_NOTHING, default=1, verbose_name='Статус')
    ticket_duration = models.DurationField('Время простоя', blank=True, null=True)
    ticket_worker = models.ForeignKey(Worker, on_delete=models.DO_NOTHING, verbose_name='Работник', blank=True, null=True)
    ticket_sender = models.CharField('Заявитель', max_length=50, null=True, blank=True)
    def close(self):
        self.ticket_status_id = 2
        self.save()

    def duration_save(self):
        if self.ticket_status_id == 2:
            self.ticket_duration = (timezone.now().astimezone() - self.ticket_date)
            self.save()

    @property
    def duration_get(self):
        ticket_duration=timezone.now().astimezone() - self.ticket_date
        if ticket_duration.days > 0:
            return str(ticket_duration).split(".")[0].replace("days", "Дней").replace("day", "День")
        else:
            return str(ticket_duration).split(".")[0]

    @property
    def duration_time(self):
        return str(self.ticket_duration).split(".")[0].replace("days", "Дней").replace("day", "День")

    @property
    def close_time(self):
        if self.ticket_duration:
            closed = self.ticket_date + self.ticket_duration
            return closed
    @property
    def ticket_date_tz(self):
        return self.ticket_date.astimezone()

    @property
    def content_normalize(self):
        if self.ticket_content.isupper() and len(self.ticket_content) > 5:
            return self.ticket_content.capitalize()
        else:
            return self.ticket_content

    def status(self):
        status = TicketStatus.objects.get(pk=self.ticket_status.id)
        return status

    status.admin_order_field = 'ticket_status'
    status.boolean = False
    status.short_description = 'Статус заявки'

    def __str__(self):
        return 'Открыта: %s, статус: %s' % (self.ticket_date.strftime("%Y/%m/%d %H:%M"), self.ticket_status)

    class Meta:
        verbose_name = "Заявка"
        verbose_name_plural = "07. Заявки"


class Comments(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, verbose_name='Номер заявки')
    comment_date =  models.DateTimeField('Дата публикации')
    comment_content = models.CharField('Содержание', max_length=500)
    comment_user = models.CharField('Пользователь', max_length=50, null=True)
    def __str__(self):
        return '%s %s' % (self.comment_date.strftime("%Y/%m/%d %H:%M"), self.comment_content)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "07. Комментарии"


class FUR_group(models.Model):
    group_name = models.CharField('Название группы', max_length=50)
    def __str__(self):
        return '%s' % (self.group_name)
    class Meta:
        verbose_name = "Группа причин заявок"
        verbose_name_plural = "09. Группы причин заявок"


class FUReason(models.Model):
    reason_group = models.ForeignKey(FUR_group, on_delete=models.CASCADE, verbose_name='Группа списка причин')
    reason_text = models.TextField('Содержание', max_length=2000)
    def __str__(self):
        return '%s' % (self.reason_text)
    class Meta:
        verbose_name = "Часто используемая причина"
        verbose_name_plural = "09. Часто используемые причины"

base/templates/base/content_page.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="ROBOTS" content="ALL" />
    <meta name="MSSmartTagsPreventParsing" content="true" />
    <meta name="Copyright" content="germka" />
    <title>{% block title %} Мастер-Лифт {% endblock%}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'base/style.css' %}">
</head>

<!--HEADER-->
<header class="header">
    <div class="header_midle">
    <div class="page_title"><span class="header_text">{% block header %}{% endblock %}
    </span>
    </div>

    <div class="top_menu">
    {% block top_menu %}
        {% include "base/top_menu.html" %}
    {% endblock %}
    </div>

    {% if usermenu != "false" %}
    <div class="user_menu">
        <span class="header_user">{{ request.user.get_full_name }}</span>
        <a href="{% url 'base:logout' %}"><span class="header_logout">Выход</span></a>
    </div>
    {% endif %}
    </div>
</header>
<!--END HEADER-->

<!--CONTENT-->
<div class="demo-ribbon"></div>
<div class="content_wrap">
<div class="index_table" id="index_table">
{% block content %}
{% endblock %}
</div>
{% block paginator %}{% endblock %}
</div>
</div>
<!--END CONTENT-->

base/templates/base/detail.html
{% extends "base/content_page.html" %}

{% block header %}Заявка №{{ticket.id}} от {{ ticket.ticket_date }}{% endblock %}

{% block top_menu %}{% include "base/top_menu.html" with new='true' index='true' summary='true' %}{% endblock %}

{% block content %}

<div class="new_ticket_header">
    {% if request.META.HTTP_REFERER != request.build_absolute_uri %}
        <a href="{{ request.META.HTTP_REFERER }}" class="turn_back">Вернуться назад</a>
    {% endif %}
</div>

<div class="detail_ticket_row">
    <span class="detail_name">Адрес заявки</span>
    <span class="detail_info">{{ ticket.ticket_str }}, дом {{ ticket.ticket_build }}{% if ticket.ticket_build_housing %}, корп. {{ ticket.ticket_build_housing }}{% endif %}{% if ticket.ticket_par %}, парадная {{ ticket.ticket_par }}{% endif %}{% if ticket.ticket_obj_type %}, тип лифта:{% elif ticket_object.obj_type %}, тип лифта:{% endif %}
    {%comment%}
    
    {%endcomment%}
    {% if request.user.is_staff or ticket.ticket_status_id != 2 and ticket.ticket_object and objects_list|length > 1 %}
        <input list="objects" id="change_object" name="change_object" size="15" autocomplete="off" hidden form="edit_ticket_form" class="ticket_editor">
        <datalist id="objects">
        {% for object in objects_list %}
            <option>{{ object.obj_type }}</option>
        {% endfor %}
        </datalist>
        <a href="javascript:void(0)" id="edit_obj" class="edit_ticket_link">{% if ticket.ticket_obj_type %}{{ ticket.ticket_obj_type }}{% else %}{{ticket_object.obj_type}}{% endif %}</a>
    {% else %}
        {% if ticket.ticket_obj_type %}{{ ticket.ticket_obj_type }}{% else %}{{ticket_object.obj_type}}{% endif %}
    {% endif %}
    </span>
    <span class="detail_ticket_type">{{ ticket.ticket_type }}</span>
</div>
<div class="detail_ticket_row">
    <span class="detail_name">Открыта: </span>
    <span class="detail_info">{{ ticket.ticket_user.first_name }} {{ ticket.ticket_user.last_name }} [{{ ticket.ticket_date|time:"H:i" }}]</span>
    <span class="detail_ticket_type">{% if ticket.ticket_sender %}Заявитель: {{ ticket.ticket_sender }}{% endif %}</span>
</div>
<div class="detail_ticket_row">
    <span class="detail_name">Статус: </span>
    <span class="detail_info">
        {% if request.user.is_staff and ticket.ticket_status_id == 2 %}
            <input type="checkbox" id="open_ticket" name="reopen_ticket" size="15" autocomplete="off" hidden form="edit_ticket_form" class="ticket_editor">
            <label for="open_ticket" id="open_ticket_label" hidden>Открыть заявку</label>
            <a href="javascript:void(0)" id="edit_status" class="edit_ticket_link">{% endif %}
        {% if ticket_message %}{{ ticket_message }}{% else %}{{ ticket.ticket_status }}{% if request.user.is_staff and ticket.ticket_status_id == 2 %}</a>{% endif %}
        &nbsp
        {% if request.user.is_staff and ticket.ticket_status_id == 2 %}
            <input type="datetime-local" name="new_ticket_date" id="ticket_date" value="{{ date_now }}" form="edit_ticket_form" class="ticket_editor" hidden disabled>
            <a href="javascript:void(0)" id="edit_date" class="edit_ticket_link">{% endif %}
        {% if ticket.close_time %}[{{ ticket.close_time|time:"H:i" }}] [{{ ticket.close_time|date }}]{% endif %}{% endif %}{% if request.user.is_staff and ticket.ticket_status_id == 2 %}</a>{% endif %}
    </span>
</div>
<div class="detail_ticket_row">
    <span class="detail_name">Время простоя: </span>
    <span class="detail_info">
    {% if ticket.ticket_duration %}
        {% if ticket.duration_time %}
            {{ ticket.duration_time }}
        {% endif %}
    {% else %}
        {% if ticket.duration_get %}
            {{ ticket.duration_get }}
        {% else %}
            {{ ticket.ticket_date|timesince }}
        {% endif %} 
    {% endif %}
    </span>
</div>

{% if ticket.ticket_status_id != 2 %}
    <form id="ticket_close" action="{% url 'base:ticket_close' ticket.id %}" method="post" class="ticket_close_form">
{% csrf_token %}

{% if exact_message %}
<div class="detail_ticket_row">
    <span class="detail_name"></span>
    <span class="detail_info">{{ exact_message }}</span>
</div>
{% endif %}

{% if exact_preview.obj_number %}
<div class="detail_ticket_row">
    <span class="detail_name">Номер лифта: </span>
    <span class="detail_info"> {{ exact_preview.obj_number }} </span>
</div>
{% endif %}

{% if exact_preview.id %}<input type="hidden" name="ticket_obj" value="{{ exact_preview.id }}">{% endif %}

{% if object_exact %}
    {% if object_exact.obj_type %}
        {{ object_exact.obj_type }}
    {% else %}
    <div class="detail_ticket_row">
        {% if exact_message %}
            <span class="detail_name">{{ exact_message }}</span>
        {% endif %}
        <span class="detail_info"><input list="object_exact" name="obj_exact" placeholder="Тип лифта" size="20" autocomplete="off"></span>
        <datalist id="object_exact">
        {% for obj in object_exact %}
            <option>{{ obj.obj_type }}</option>
        {% endfor %}
        </datalist>
    </div>
    {% endif %}
{% endif %}

{% if workers %}
    <div class="detail_ticket_row">
    <span class="delail_name">Исполнитель:</span>
        <span class="detail_info"><input list="worker_exact" name="worker_exact" placeholder="Исполнитель" size="20" autocomplete="off" required></span>
        <datalist id="worker_exact">
        {% for worker in workers %}
            <option>{{ worker.full_name }}</option>
        {% endfor %}
        </datalist>
    </div>
{% endif %}

{% comment %}
{% if ticket.ticket_status_id != '2' %}
    <div class="ticket_close"><input type="submit" id="ticket_close_button" value="Закрыть заявку" class="ticket_close_button send_button"></div>
{% endif %}
{% endcomment %}

{% if error_message %}
<div class="detail_ticket_row error_message">
    <span>{{ error_message }}</span>
</div>
{% endif %}

</form>
{% endif %}

{% if ticket.ticket_worker %}
<div id="ticket_content_row" class="ticket_content_row detail_ticket_row">
    <span class="detail_name">Исполнитель: </span>
    <span id="ticket_content_info" class="ticket_content_info detail_info">
    {% if request.user.is_staff and ticket.ticket_worker %}
    <input list="ticket_workers" id="ticket_workers_list" name="new_worker" placeholder="Новый работник" size="20" autocomplete="off" hidden form="edit_ticket_form" class="ticket_editor">
    <a href="javascript:void(0)" id="edit_worker" class="edit_ticket_link">{{ ticket.ticket_worker.full_name }}</a>
        <datalist id="ticket_workers">
        {% for worker in workers %}
            <option>{{ worker.full_name }}</option>
        {% endfor %}
        </datalist>
    {% else %}
        {{ ticket.ticket_worker.full_name }}
    {% endif %}
    </span>
</div>
{% endif %}

<div id="ticket_content_row" class="ticket_content_row detail_ticket_row">
    <span class="detail_name" style="position:absolute">Причина: </span>
    <div class="detail_ticket_content">
        <textarea form="{% if request.user.is_staff %}edit_ticket_form{% else %}ticket_close{% endif %}" class="detail_info" name="{% if request.user.is_staff %}new_content{% else %}ticket_content{% endif %}" id="ticket_content" placeholder="{{ content_value|default:"Текст заявки" }}" cols="80" rows="4" autocomplete="off" class="new_ticket_content">{% if ticket.ticket_content %}{{ ticket.ticket_content }}{% endif %}</textarea>
        <a href="javascript:void(0)" id="reset_content" class="edit_ticket_link reset_content">Отменить изменения</a>
    </div>
</div>

<a href="javascript: void(0)" class="fur" id="fur">Причины</a>


<div class="fur_block" id="fur_block" hidden>

    {% for group in FUR|dictsort:"id" %}
    <a href="javascript: void(0)" class="reason_group_link" id="group_link_{{ group.id }}"><span class="reason_group">{{ group.id }}. {{ group }}</span></a>
    <ul id="reason_list_{{ group.id }}" class="reason_list" hidden>
        {% for reason in group.fureason_set.all|dictsort:"reason_text" %}
            <li>{{ reason }}</li>
        {% endfor %}
    </ul>
    {% empty %}
        Пока ничего нет</br>
    {% endfor %}

    <input list="FUR_list" id="FUReason" name="FUReason" placeholder="Причина" class="reason_list">
    <datalist id="FUR_list">
    {% for group in FUR|dictsort:"id" %}
        {% for reason in group.fureason_set.all|dictsort:"reason_text" %}
            <option>{{ reason }}</option>
        {% endfor %}
    {% empty %}
        Пока ничего нет</br>
    {% endfor %}

</div>

<div class="comments">
    <span class="detail_name">Комментарии:</span>
    <div>
        {% for comment in ticket.comments_set.all|dictsort:"comment_date" %}
            <div class="comment_row"><span class="comment_num">№{{ forloop.counter }}</span>
                {% if comment.comment_date %}<span class="comment_date">[{{ comment.comment_date }}]</span>{% endif %}
                {% if comment.comment_user %}<span class="comment_user">{{ comment.comment_user }} написал(a):</span>{% endif %}
                </br>
                {% if comment.comment_content %}<span class="comment_content">{{ comment.comment_content }}</span>{% endif %}
                {% if message %}{% if forloop.last %}<div class="comment_add_message">{{ message }}</div>{% endif %}{% endif %}
            </div>
        {% empty %}
            <span class="no_data">Пока нет ни одного комментария</p>
        {% endfor %}
    <a href="#" class="fur" id="comment_form_show">комментировать</a>
</div>

<form id="new_comment_form" action="{% url 'base:ticket_detail' ticket.id %}" method="post" class="new_comment_form" {% if not message %}hidden{% endif %}>
    {% if error_message %}<div class="error_message">{{ error_message }}</div>{% endif %}
    {% csrf_token %}
    <div class="comment_content_wrap">
        <textarea name="comment_content" required placeholder="Содержание комментария" cols="50" rows="4" class="new_comment_content"></textarea>
    </div>
    <input class="send_button" type="submit" value="Отправить комментарий">
</form>

{% if request.user.is_staff %}
<form id="edit_ticket_form" action="{% url 'base:ticket_edit' ticket.id %}" method="post" class="ticket_editor_form">
{% csrf_token %}
<input type="submit" id="save_ticket" value="Сохранить изменения" class="send_button save_button">
</form>
{% endif %}

{% if ticket.ticket_status_id != 2 and request.user.groups.first.id != 2 %}
    <div style="position:relative"><input type="submit" id="close_ticket" value="Закрыть заявку" class="send_button" form="ticket_close"></div>
{% endif %}
</div>

{% load static %}
<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="{% static 'base/menu.js' %}"></script>
<script type="text/javascript" src="{% static 'base/list.js' %}"></script>
<script type="text/javascript" src="{% static 'base/fur.js' %}"></script>
{% if request.user.is_staff %}
<script type="text/javascript" src="{% static 'base/ticket_editor.js' %}"></script>
{% endif %}

{% endblock %}

base/templates/base/index.html
{% extends "base/content_page.html" %}

{% block header %}Список заявок{% endblock %}

{% block top_menu %}{% include "base/top_menu.html" with new='true' filter='true' summary='true' %}{% endblock %}

{% block content %}

{% if not no_filter %}
<div class="index_no_filter">
    <span><a href="{% url 'base:ticket_index' %}">отменить фильтры</a></span>
</div>
{% endif %}

{% if ticket_list %}
    {% for ticket in ticket_list %}
        {% cycle 'normal_row' 'dark_row' as rowtype silent %}
        {% ifchanged %}
        <div class="ticket_row index_splitter ">
            {% if splitter == "area" %}<span  class="index_row_item">{{ ticket.ticket_str.area }}</span>
            {% elif splitter == "str" %}<span  class="index_row_item">{{ ticket.ticket_str }}</span>
            {% elif splitter == "status" %}<span  class="index_row_item">{{ ticket.ticket_status }}</span>
            {% endif %}
            <span  class="index_row_item">{{ ticket.ticket_date_tz.date }}</span>
            {% if not forloop %}{% resetcycle rowtype %}{% endif %}
        </div>
        {% endifchanged %}
        <div class="ticket_row_{{ forloop.counter }} ticket_row {{ rowtype }}">
            <a href="{% url 'base:ticket_detail' ticket.id %}" title="Открыть заявку №{{ticket.id}}">
            <span  class="ticket_date index_row_item"> {{ ticket.ticket_date_tz|time:"H:i" }}{% if ticket.close_time %}/{{ ticket.close_time|time:"H:i" }}{% endif %}</span>
            </a>
            <a href="{% url 'base:ticket_detail' ticket.id %}" title="Открыть заявку №{{ticket.id}}">
            <span class="ticket_adress index_row_item">{{ ticket.ticket_str }}, д. {{ ticket.ticket_build }}{% if ticket.ticket_build_housing %}, к. {{ ticket.ticket_build_housing }}{% endif %}{% if ticket.ticket_par %}, пар. {{ ticket.ticket_par }}{% endif %}{% if ticket.ticket_obj_type %}, {{ ticket.ticket_obj_type|truncatechars:14 }}{% else %}, {{ ticket.ticket_object.obj_type|truncatechars:14|default_if_none:"неопределен" }}{% endif %}</span>
            </a>
            <a href="{% url 'base:ticket_detail' ticket.id %}" title="Тип/Причина/Исполнитель заявки">
            <span class="ticket_type index_row_item">{{ ticket.ticket_type.type_name }}</span>
            <span class="ticket_content index_row_item">{{ ticket.content_normalize|truncatechars:36 }} 
            {% if ticket.comments_set.count > 0 %}
                <span class="ticket_comment_count" title="Количество комментариев">({{ticket.comments_set.count}})</span>
            {% endif %}
            </span>
            <span class="index_ticket_worker index_row_item">{{ ticket.ticket_worker.last_name|truncatechars:10 }}</span>
            </a>
            {% load static %}
            <a href="{% url 'base:index_filter' ticket.ticket_status.status %}" title='Отфильтровать заявки со статусом "{{ ticket.ticket_status }}"'>
            <span class="ticket_status index_row_item {% if ticket.ticket_status.id == 1 %}red_text{% elif ticket.ticket_status.id == 2  %}green_text{% endif %}">
                <span class="ticket_num">#{{ ticket.id }}</span>
                <img class="ticket_status_icon" src="{% if ticket.ticket_status_id == 2 %}{% static 'admin/img/icon-yes.svg' %}" alt="Закрыта"{% else %}{% static 'admin/img/icon-no.svg' %}" alt="{{ ticket.ticket_status }}"{% endif %}>
            </span>
        </a>
        </div>
    {% endfor %}
{% else %}
    <div class=ticket_row>
        <span style="text-align:center">Пока что заявок нет</span>
    </div>
{% endif %}



{% endblock %}

{% block paginator %}
    {% include "base/paginator.html" %}
{% endblock %}